version: '3.8'

services:
    app:
        build: .
        working_dir: /application
        environment:
            APP_ENV:  'local'
            TIMEZONE: 'Asia/Almaty'
        volumes:
            - ./laravel:/application
            - ./conf/php.ini:/etc/php-custom.d/php.ini
        ports:
            - 9000
        restart:     unless-stopped

    web:
        image: nginx
        ports:
            - 80:80
        volumes:
            - ./conf/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
            - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./laravel:/application

    db:
        image: postgres:13
        restart: always
        environment:
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: 'postgres'
            POSTGRES_DB: 'postgres'
            SCHEMA: 'public'
        ports:
            - 54134:5432
        volumes:
            - ./conf/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
            - ./conf/postgres-data:/var/lib/postgresql/data

            #npm:
        #image: "node:19-bullseye"
        #user: "node"
       # working_dir: /application
        #environment:
        #    - NODE_ENV=production
        #volumes:
        #    - ./laravel:/application
        #ports:
         #   - "3000:3000"
        #command: ["npm", "run", "dev" ]